// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-AV73RiMrrflbayX0UKBy88Y_cBsY3Rs',
    appId: '1:637813790730:web:e23a1faf6dcbe8815a67f3',
    messagingSenderId: '637813790730',
    projectId: 'chatapp-d9e3a',
    authDomain: 'chatapp-d9e3a.firebaseapp.com',
    storageBucket: 'chatapp-d9e3a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_EiNcRrJvZi0_XwPl_q4reRPi3KOe3tI',
    appId: '1:637813790730:android:0c33e01ef7c6b3ea5a67f3',
    messagingSenderId: '637813790730',
    projectId: 'chatapp-d9e3a',
    storageBucket: 'chatapp-d9e3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB-CtZgaRb4lljV-HKyWJAOpf2aLJrJYI',
    appId: '1:637813790730:ios:e474a0b629f8db085a67f3',
    messagingSenderId: '637813790730',
    projectId: 'chatapp-d9e3a',
    storageBucket: 'chatapp-d9e3a.appspot.com',
    iosBundleId: 'com.gaganamol.attendanceCounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB-CtZgaRb4lljV-HKyWJAOpf2aLJrJYI',
    appId: '1:637813790730:ios:5005a525e79a49785a67f3',
    messagingSenderId: '637813790730',
    projectId: 'chatapp-d9e3a',
    storageBucket: 'chatapp-d9e3a.appspot.com',
    iosBundleId: 'com.gaganamol.attendanceCounter.RunnerTests',
  );
}
